version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 20
  reviewers:
  - unhappychoice
  ignore:
  - dependency-name: com.github.triplet.play
    versions:
    - 3.2.0-agp4.2-2
    - 3.3.0-agp4.2
